 name: Build and Push dbt Image
 on:
  workflow_dispatch:
  push:
    branches: ["main", "feature/*"]
    paths:
      - "dbt/**"
      - "docker/Dockerfile.dbt"
      - ".github/workflows/docker-build.yml"
 jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create Snowflake key file
        run: |
          mkdir -p /tmp/ssh
          echo "${{ secrets.SNOWFLAKE_PRIVATE_KEY_P8 }}" > /tmp/ssh/snowflake_rsa_key.p8
          chmod 600 /tmp/ssh/snowflake_rsa_key.p8
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile.dbt
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dbt_images:latest
          build-args: |
            SNOWFLAKE_ACCOUNT=${{ secrets.SNOWFLAKE_ACCOUNT }}
      - name: Publish image with key (multi-stage alternative)
        run: |
          # Simple rebuild copying key into image (if you prefer this pattern):
          docker build -f docker/Dockerfile.dbt -t ${{ secrets.DOCKERHUB_USERNAME }}/dbt_images:latest .
          docker create --name tmp ${{ secrets.DOCKERHUB_USERNAME }}/dbt_images:latest
          docker cp /tmp/ssh/snowflake_rsa_key.p8 tmp:/root/.ssh/snowflake_rsa_key.p8
          docker commit tmp ${{ secrets.DOCKERHUB_USERNAME }}/dbt_images:latest
          docker rm tmp
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/dbt_images:latest